### ISSUE TITLE
Что если использовать String.join, создав предварительно массив из "?" нужного количества?

### ISSUE THREAD

**Issue by coursar** [KonAnd13/Avito-inMemory-JdbcImpl#2]
https://github.com/KonAnd13/Avito-inMemory-JdbcImpl/blob/af28878bfdd5603424bbdf6f18f088c8ace8fd9a/src/main/java/ru/itpark/repository/HouseRepositoryJdbcImpl.java#L76-L79

**Comment by KonAnd13** [comment]
@coursar , Спасибо, так выглядит лучше и понятней.
https://github.com/KonAnd13/Avito-inMemory-JdbcImpl/blob/baf20a17de2012373a11e4fce09ade5ad159fd96/src/main/java/ru/itpark/repository/HouseRepositoryJdbcImpl.java#L72-L97
